version: "3.3"
services:
  nginx:
    container_name: nginx
    image: nginx:1.11.10-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    links:
      - php
  php:
    container_name: php
    build: ./php
    volumes:
      - ./src:/var/www/html
